 
target:ch22b009.tex
	latex ch22b009.tex
	 
 
	latex ch22b009.tex
	latex ch22b009.tex
	
	
	bibtex ch22b009
	
	bibtex ch22b009
	pdflatex ch22b009.tex
	bibtex ch22b009
	pdflatex ch22b009.tex
	bibtex ch22b009
	latex ch22b009.tex
	dvipdf ch22b009.dvi

	rm -f ch22b009.aux ch22b009.bbl ch22b009.log ch22b009.dvi ch22b009.blg fig-eps-converted-to.pdf
	xdg-open ch22b009.pdf
